package org.example.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.List;
import java.util.Map;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName="employees")
public class Employee {

    @DynamoDBHashKey(attributeName = "employeeId")
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private Long tokens;

    @DynamoDBAttribute
    private List<String>productIdList;


    public Employee(Map<String, String> userAttributes) {

        this.id = userAttributes.get("sub");
        this.name = userAttributes.get("given_name");
        this.lastName = userAttributes.get("family_name");
        this.email = userAttributes.get("email");
        this.tokens = 0L;

    }
}
