package org.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

//@Data
//@AllArgsConstructor
//@NoArgsConstructor
//public class Innovation {
//
//    private int id;
//    private String title;
//    private String description;
//
//    public Innovation(String title, String description) {
//        this.title = title;
//        this.description = description;
//    }
//}


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName="innovation")
public class Innovation {


    @DynamoDBHashKey(attributeName = "innovationId")
    @DynamoDBAutoGeneratedKey
    private String id;


    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    public Innovation(String title, String description) {
        this.title = title;
        this.description = description;
    }
}
