package org.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.example.enums.InnovationStatus;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName="innovation")
public class Innovation {


    @DynamoDBHashKey(attributeName = "innovationId")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private InnovationStatus status;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String comment;

    public Innovation(String title, String description, InnovationStatus status, String userId) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.userId = userId;
    }

}
