package org.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.example.enums.InnovationStatus;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName = "innovation-uros")
public class Innovation {

    @DynamoDBRangeKey(attributeName = "innovationId")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBHashKey(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private InnovationStatus innovationStatus;

    @DynamoDBAttribute
    private String comment;

    public Innovation(String title, String description, InnovationStatus status, String userId) {
        this.title = title;
        this.description = description;
        this.innovationStatus = status;
        this.userId = userId;
    }
}
